import { BrandInfo, ContactChannel, UserProfile } from './types';

export const USER_PROFILE: UserProfile = {
  name: 'Ulises Hernández',
  title: 'Key Account Manager',
  division: 'Belting & Industrial Solutions',
  company: 'AMMEGA Group',
  companyTagline: 'The Power of Motion',
  companyDescription: 'Líder global en soluciones integrales de bandas de transporte, transmisión de potencia síncrona y conducción de fluidos para la industria alimentaria, manufactura y automotriz.',
  companyWebsite: 'https://ammega.com/',
  websiteSummary: 'Catálogo y portal oficial con soluciones de ingeniería en bandas transportadoras sintéticas (Ammeraal Beltech), correas de transmisión (Megadyne) y mangueras industriales (Jason Industrial).',
  projectsSectionTitle: 'Proyectos',
  phoneDisplay: '(33) 1618 0902',
  phoneRaw: '+523316180902',
  whatsappNumber: '523316180902',
  email: 'Ulises.FH@gmail.com',
  coverageZone: 'Guadalajara / Occidente & Bajío · México',
  brandsUrl: 'https://ammega.com/brands/',
  corporateUrl: 'https://ammega.com/',
  location: 'Guadalajara, Jalisco, México',
  bio: 'Especialista en soluciones integrales para transporte de materiales, transmisión de potencia síncrona y conducción de fluidos para la industria manufacturera, alimentaria y automotriz en la región Occidente y Bajío.',
  status: 'disponible',
};

export const BRANDS: BrandInfo[] = [
  {
    id: 'ammeraal',
    name: 'Ammeraal Beltech',
    category: 'Bandas Transportadoras & Procesamiento',
    categoryPill: 'Conveying',
    color: '#2563eb',
    badge: 'Líder en Transporte Higiénico',
    description:
      'Líder global en diseño y fabricación de bandas transportadoras sintéticas para procesamiento de grado alimenticio, bandas modulares plásticas uni-chains y bandas sinfín.',
    keyProducts: [
      'Bandas sintéticas de PVC y Poliuretano (PU)',
      'Bandas modulares uni-chains®',
      'Bandas dentadas y correas de sincronización Rapplon®',
      'Bandas homogéneas de fácil limpieza Soliflex®',
      'Sistemas ZipLink® para cambio rápido sin vulcanizado',
    ],
    subcategories: [
      {
        id: 'ab-modulares',
        title: 'Bandas Modulares uni-chains®',
        description: 'Bandas plásticas articuladas de alta resistencia para transporte en curvas, grado alimenticio y sanitización rápida sin acumulaciones.',
        linkUrl: 'https://www.ammeraalbeltech.com/es/productos/bandas-modulares/',
        badge: 'Curvas & Grado Alimenticio',
      },
      {
        id: 'ab-sinteticas',
        title: 'Bandas Sintéticas de Proceso (PVC y PU)',
        description: 'Bandas multicapa con recubrimientos especiales para corte, congelación, horneado e inclinaciones en líneas continuas.',
        linkUrl: 'https://www.ammeraalbeltech.com/es/productos/bandas-sinteticas/',
        badge: 'Higiene FDA / USDA',
      },
      {
        id: 'ab-soliflex',
        title: 'Bandas Homogéneas Soliflex®',
        description: 'Termoplástico macizo sin telas internas; previene contaminación cruzada y reduce hasta un 70% el consumo de agua en lavado.',
        linkUrl: 'https://www.ammeraalbeltech.com/es/productos/bandas-homogeneas-soliflex/',
        badge: 'Máxima Inocuidad',
      },
      {
        id: 'ab-ziplink',
        title: 'Sistemas ZipLink®',
        description: 'Cierre mecánico espiral integrado que permite ensamblar o reemplazar la banda en minutos sin prensas pesadas de calor.',
        linkUrl: 'https://www.ammeraalbeltech.com/es/productos/ziplink/',
        badge: 'Mantenimiento Rápido',
      },
    ],
    industries: [
      'Alimentos y Bebidas',
      'Logística y Centros de Distribución',
      'Industria del Empaque',
      'Aeropuertos',
      'Tabaco y Agricultura',
    ],
    officialUrl: 'https://www.ammeraalbeltech.com/es/',
    catalogUrl: 'https://www.ammeraalbeltech.com/es/productos/',
  },
  {
    id: 'megadyne',
    name: 'Megadyne',
    category: 'Transmisión de Potencia',
    categoryPill: 'Power Trans',
    color: '#e11d48',
    badge: 'Alta Precisión Síncrona',
    description:
      'Pionero mundial en correas sincrónicas de poliuretano, correas dentadas de caucho para transmisiones automotrices e industriales, correas en V y poleas asociadas.',
    keyProducts: [
      'Correas síncronas de poliuretano Megapower® e Isoran®',
      'Bandas dentadas abiertas para automatización Megalinear®',
      'Correas en V de alto rendimiento Oleostatic®',
      'Recubrimientos especiales (Linatex, Tenax, NBR, foam)',
      'Poleas y componentes de transmisión a medida',
    ],
    subcategories: [
      {
        id: 'mg-isoran',
        title: 'Correas Síncronas Isoran® & Megapower®',
        description: 'Transmisión positiva sin patinaje para motores de alta potencia y aplicaciones con requerimiento de sincronismo milimétrico.',
        linkUrl: 'https://megadynegroup.com/es/productos/correas-dentadas',
        badge: 'Sincronía & Cero Resbalamiento',
      },
      {
        id: 'mg-megalinear',
        title: 'Bandas Dentadas Abiertas Megalinear®',
        description: 'Rollos continuos en poliuretano con cuerdas de acero o Kevlar para posicionamiento lineal en robótica, elevación y CNC.',
        linkUrl: 'https://megadynegroup.com/es/productos/correas-abiertas',
        badge: 'Robótica y Automatización',
      },
      {
        id: 'mg-oleostatic',
        title: 'Correas Trapeciales (En V) Oleostatic®',
        description: 'Correas de caucho para servicio pesado con resistencia comprobada a la tensión continua, aceites y calor en planta.',
        linkUrl: 'https://megadynegroup.com/es/productos/correas-trapeciales',
        badge: 'Heavy Duty',
      },
      {
        id: 'mg-poleas',
        title: 'Poleas Dentadas y Accesorios a Medida',
        description: 'Mecanizado y cálculo de transmisiones completas optimizadas para reducir desgaste y consumo energético.',
        linkUrl: 'https://megadynegroup.com/es/productos/poleas-y-componentes',
        badge: 'Cálculo de Transmisión',
      },
    ],
    industries: [
      'Automotriz y Líneas de Ensamble',
      'Cerámica, Mármol y Vidrio',
      'Maquinaria para Trabajo de Madera',
      'Impresión y Artes Gráficas',
      'Equipos Médicos y Farmacéutica',
    ],
    officialUrl: 'https://megadynegroup.com/',
    catalogUrl: 'https://megadynegroup.com/es/productos',
  },
  {
    id: 'jason',
    name: 'Jason Hose Solutions',
    category: 'Mangueras y Conducción de Fluidos',
    categoryPill: 'Industrial',
    color: '#991b1b',
    badge: 'Servicio Pesado y Minería',
    description:
      'Fabricante confiable de mangueras industriales para succión y descarga de agua, vapor, hidrocarburos, químicos corrosivos, sistemas hidráulicos y acoples de conexión rápida.',
    keyProducts: [
      'Mangueras industriales para químicos y solventes',
      'Mangueras de vapor a alta temperatura y presión',
      'Mangueras para manejo de materiales abrasivos y cemento',
      'Mangueras hidráulicas estándar y especiales',
      'Acoples rápidos tipo Camlock, conexiones y abrazaderas',
    ],
    subcategories: [
      {
        id: 'jh-quimicas',
        title: 'Mangueras para Químicos y Solventes (UHMWPE)',
        description: 'Tubo interior altamente resistente a químicos agresivos, ácidos y solventes para trasvase seguro en pipas y plantas químicas.',
        linkUrl: 'https://jasonhosesolutions.com/products/industrial-hoses/',
        badge: 'Química & Petroquímica',
      },
      {
        id: 'jh-vapor',
        title: 'Mangueras de Vapor y Alta Temperatura',
        description: 'Diseñadas para vapor saturado y sobrecalentado de hasta 232°C (450°F) con refuerzo de doble trenza de acero.',
        linkUrl: 'https://jasonhosesolutions.com/products/industrial-hoses/',
        badge: 'Vapor Seguro',
      },
      {
        id: 'jh-hidraulica',
        title: 'Mangueras y Ensambles Hidráulicos',
        description: 'Líneas hidráulicas para maquinaria pesada, prensas y equipo móvil certificadas según normas SAE e ISO.',
        linkUrl: 'https://jasonhosesolutions.com/products/hydraulic-hoses/',
        badge: 'Líneas de Presión',
      },
      {
        id: 'jh-camlock',
        title: 'Acoples Camlock y Conexiones Rápidas',
        description: 'Acoplamientos herméticos en aluminio, acero inoxidable 316 y polipropileno con empaques especiales.',
        linkUrl: 'https://jasonhosesolutions.com/products/couplings-clamps/',
        badge: 'Conexión Segura',
      },
    ],
    industries: [
      'Química y Petroquímica',
      'Minería y Agregados',
      'Construcción Pesada',
      'Alimentaria y Bebidas (Mangueras FDA)',
      'Manufactura Pesada',
    ],
    officialUrl: 'https://jasonhosesolutions.com/',
    catalogUrl: 'https://jasonhosesolutions.com/products/',
  },
];

export const GROUP_METRICS = [
  { value: '40+', label: 'Países Atendidos' },
  { value: '190+', label: 'Instalaciones Globales' },
  { value: '50+', label: 'Industrias' },
  { value: '6,000+', label: 'Expertos en Movimiento' },
];

export const CONTACT_CHANNELS: ContactChannel[] = [
  {
    id: 'wa-direct',
    title: 'WhatsApp Business Directo',
    value: '+52 33 1618 0902',
    actionUrl:
      'https://wa.me/523316180902?text=Hola%20Ulises%2C%20me%20comunico%20desde%20tu%20tarjeta%20digital%20AMMEGA%20para%20cotizar%20soluciones',
    icon: 'whatsapp',
    isExternal: true,
  },
  {
    id: 'phone',
    title: 'Línea Telefónica Móvil',
    value: '(33) 1618 0902',
    actionUrl: 'tel:+523316180902',
    icon: 'phone',
    isExternal: false,
  },
  {
    id: 'email',
    title: 'Correo Corporativo',
    value: 'Ulises.FH@gmail.com',
    actionUrl: 'mailto:Ulises.FH@gmail.com?subject=Consulta%20T%C3%A9cnica%20-%20Soluciones%20AMMEGA',
    icon: 'mail',
    isExternal: false,
  },
  {
    id: 'coverage',
    title: 'Zona de Cobertura',
    value: 'Guadalajara / Occidente & Bajío · México',
    actionUrl: 'https://maps.google.com/?q=Guadalajara,Jalisco,Mexico',
    icon: 'map-pin',
    isExternal: true,
  },
  {
    id: 'portal',
    title: 'Sitio Oficial de Marcas',
    value: 'ammega.com/brands',
    actionUrl: 'https://ammega.com/brands/',
    icon: 'globe',
    isExternal: true,
  },
];
